# Generated by Django 5.0 on 2023-12-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Напишите текст, по которому сгенерируется картинка', max_length=150, verbose_name='текст для создания картинки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
